### PR TITLE
Add Dockerfiles for stretch

### PR DESCRIPTION
**Pull request by stuartpb**
This time, I'm *not* going to reflexively merge the PR without review :wink:

### CODE REVIEW

**Comment by danielmewes** [comment]
Looks good to me. Thanks for the PR @stuartpb .

Do we need to submit a PR to the official Docker repo for these to become available @dalanmiller ?

**Comment by dalanmiller** [comment]
We sure do I believe. Thank you for this @stuartpb :D

**Comment by dalanmiller** [comment]
@stuartpb it looks like other providers aren't specifying the release name in their lists, I assume this means we would make it available across all releases not just `jessie` or `stretch`? 

https://github.com/docker-library/official-images/blob/master/library/ghost

**Comment by dalanmiller** [comment]
@yosifkit should we continue to state `jessie` in our file over here? I see a lot of other projects not listing any specific Debian release. 

https://github.com/docker-library/official-images/blob/master/library/rethinkdb

**Comment by yosifkit** [comment]
The jessie in the library file is just the folder where the Dockerfile exists in your repo.  Are you wanting to do something like [python](https://hub.docker.com/r/_/python/) where you have tags for other Linux flavors?  I am not sure it makes sense for a service to need to be in different Linux flavors; the reason that python has a `wheezy` variant is that some users need to install old libraries that are only available there.  The `alpine` variants are a push to create tiny images.

We updated our [docs recently](https://github.com/docker-library/official-images#library-definition-files).  We recommend keeping the number of versions to a minimum since it is what controls the "supported tags" list that is generated for the readme on Docker Hub, while old version will remain available to `docker pull`.

**Comment by stuartpb** [comment]
Yeah - the other distro variants in this repo are really just there for use by anybody who needs RethinkDB running on a different Debian for some reason.

Ideally, the official Docker repo images would be based on Alpine Linux, per the official recommendations - would it be possible to get upstream @rethinkdb packaging RetihnkDB on that platform (in which case we could publish Dockerfiles for it and switch the official images accordingly)?

**Comment by stuartpb** [comment]
Also, @yosifkit does the library policy now mean that only supported versions should be listed in the library file (meaning that we should push a PR to remove lines for older patch-releases)?

**Comment by stuartpb** [comment]
Separate from the Alpine-ization question, I've created a PR to remove RethinkDB's unsupported versions at docker-library/official-images#1650.

**Pull request merged**
