### PR TITLE
created rethinkdb-driver Dockerfile

### PR DESCRIPTION
**Pull request by cirelli94**
Fix for issue https://github.com/rethinkdb/rethinkdb-python/issues/164

### CODE REVIEW

**Comment by gabor-boros** [comment]
Hello @cirelli94,
Maybe I missed something, but why did you rename a lot of Dockerfiles from `<os>/<db-version>/...` to `/rethinkdb/<os>/<db-version>/...`?

**Comment by cirelli94** [comment]
Yes, to add a rethinkdb-driver folder on top, because maybe one day someone will need a different os based rethinkdb-driver image...

**Comment by cirelli94** [comment]
I don't know if this is what you were expecting: I just thought that create a "driver" folder along the OSes wasn't not a clear division.
Let me know if you don't like it, I can arrange in another way.

**Comment by gabor-boros** [comment]
@cirelli94 I did not forget this PR, just thinking about it. I see your point and separating the variants could be useful on the long run.

Then the only remaining thing is to adjust the `cut_new_release.sh` according to this change. If you have no time for that I totally understand and in that case I can merge this PR now, and fix that file on my own. Should I merge the PR?

**Comment by cirelli94** [comment]
I don't know how would you like it, and I didn't understand what's supposed to do, too :smile:

**Comment by gabor-boros** [comment]
Sorry, I lost a bit for some days, but I'm back. Today I found an issue which could affect this PR based on the decision made there: https://github.com/rethinkdb/rethinkdb/issues/6824.

What do you think @cirelli94 about shipping RethinkDB with the client itself? Would it resolve your issue too?

**Comment by cirelli94** [comment]
It would be great to me.
Sure, the image would be a little more heavier in bytes, but it'll surely works better for everyone without the unexpected behavior of the need to install the driver...

**Pull request closed without merging**
