### PR TITLE
feat(healthcheck): added healthcheck test using nc and port detection

### PR DESCRIPTION
**Pull request by gjuchault**

### CODE REVIEW

**Comment by stuartpb** [comment]
Do you have an example of other official images doing this?

**Comment by stuartpb** [comment]
Closes #34

**Comment by gjuchault** [comment]
@stuartpb There is a discussion about wether healthcheck should be provided on official images.
https://github.com/docker-library/postgres/issues/282#issuecomment-310219064

**Comment by stuartpb** [comment]
Yeah, to be honest, I agree with @yosifkit's assessment there:

- "port is open" isn't a significantly greater indication of healthy operation than "process is running" (it's just as possible for a malfunction to occur without disrupting the socket or process as it would be for a malfunction to occur disrupting the socket but not the process, if not more so)
- any such more-meaningful health check that *could* be run would likely depend on the specifics of the use case
- this introduces a new dependency and (marginally) more load for, as described above, negligible practical benefit

**Comment by gjuchault** [comment]
I do agree with all the people that are writing this, but when I started using compose, healthchecks are so much useful. You might close this one if you feel that's settled and let everyone deal with it on their own. At lease they will have an idea if they want to implement a simple solution (the port one)

**Comment by stuartpb** [comment]
Closing unmerged per reasoning in https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/36#issuecomment-326398363.

**Pull request closed without merging**
